import { photo } from "./images";
import type { AppState, Host, Review } from "./types";

export const HOSTS: Host[] = [
  {
    id: "h-aminata",
    name: "Aminata Diallo",
    kind: "proprietaire",
    city: "Dakar",
    since: 2019,
    response: "Répond en moins d'une heure",
  },
  {
    id: "h-moussa",
    name: "Moussa Ndiaye",
    kind: "proprietaire",
    city: "Saly",
    since: 2021,
    response: "Répond dans la journée",
  },
  {
    id: "h-ndar",
    name: "Ndar Immobilier",
    kind: "agence",
    city: "Saint-Louis",
    since: 2014,
    response: "Équipe disponible 7j/7",
  },
];

function review(name: string, date: string, text: string): Review {
  return { id: `${name}-${date}`, name, date, text, rating: 5 };
}

const img = {
  villa: [
    photo("photo-1613490493576-7fde63acd811"),
    photo("photo-1600596542815-ffad4c1539a9"),
    photo("photo-1600585154340-be6161a56a0c"),
    photo("photo-1600607687939-ce8a6c25118c"),
    photo("photo-1600566753190-17f0baa2a6c3"),
  ],
  apt: [
    photo("photo-1502672260266-1c1ef2d93688"),
    photo("photo-1560448204-e02f11c3d0e2"),
    photo("photo-1522708323590-d24dbb6b0267"),
    photo("photo-1493809842364-78817add7ffb"),
  ],
  beach: [
    photo("photo-1499793983690-e29da59ef1c2"),
    photo("photo-1520250497591-112f2f40a3f4"),
    photo("photo-1571896349842-33c89424de2d"),
    photo("photo-1507525428034-b723cf961d3e"),
  ],
  lodge: [
    photo("photo-1542718610-a1d656d1884c"),
    photo("photo-1449158743715-0a90ebb6d2d8"),
    photo("photo-1470770841072-f978cf4d019e"),
    photo("photo-1505693416388-ac5ce068fe85"),
  ],
  colonial: [
    photo("photo-1505691938895-1758d7feb511"),
    photo("photo-1616594039964-ae9021a400a0"),
    photo("photo-1618221195710-dd6b41faaea6"),
    photo("photo-1560185127-6ed189bf02f4"),
  ],
  loft: [
    photo("photo-1600210492486-724fe5c67fb0"),
    photo("photo-1600607687644-c7171b42498b"),
    photo("photo-1600566753086-00f18fb6b3ea"),
    photo("photo-1600585154526-990dced4db0d"),
  ],
  family: [
    photo("photo-1564013799919-ab600027ffc6"),
    photo("photo-1570129477492-45c003edd2be"),
    photo("photo-1600585154340-be6161a56a0c"),
    photo("photo-1600047509807-ba8f99d2cdbc"),
  ],
  studio: [
    photo("photo-1536376072261-38c75010e6c9"),
    photo("photo-1598928506311-c55ded91a20c"),
    photo("photo-1595526114035-0d45ed16cfbf"),
    photo("photo-1617103996702-96ff29b1c467"),
  ],
  abidjan: [
    photo("photo-1600607687920-4e2a09cf159d"),
    photo("photo-1600585152220-90363fe7e115"),
    photo("photo-1600573472592-401b489a3cdc"),
    photo("photo-1600566752355-35792bedcfea"),
  ],
  riad: [
    photo("photo-1582719478250-c89cae4dc85b"),
    photo("photo-1542314831-068cd1dbfeeb"),
    photo("photo-1578683010236-d716f9a3f461"),
    photo("photo-1590494165264-1ebe3602eb80"),
  ],
  paris: [
    photo("photo-1502672023488-70e25813eb80"),
    photo("photo-1554995207-c18c203602cb"),
    photo("photo-1616486338812-3dadae4b4ace"),
    photo("photo-1560185007-cde436f6a4d0"),
  ],
};

export function createInitial(): AppState {
  return {
    role: "voyageur",
    saved: [],
    listings: [
      {
        id: "villa-almadies",
        title: "Villa océan, piscine face aux Almadies",
        city: "Dakar",
        country: "Sénégal",
        neighborhood: "Almadies",
        mode: "sejour",
        type: "villa",
        price: 85_000,
        currency: "XOF",
        guests: 8,
        bedrooms: 4,
        beds: 5,
        baths: 3,
        surface: 280,
        rating: 4.96,
        reviewsCount: 38,
        images: img.villa,
        lat: 14.7458,
        lng: -17.5192,
        description:
          "La villa regarde l'Atlantique depuis les Almadies. Le séjour s'ouvre sur la terrasse, la piscine reste dans le vent du soir, et les chambres sont tenues à l'écart de la route.\n\nSe Loger au Sénégal s'occupe de l'accueil, du linge et du ménage. Vous entrez sans passer par un intermédiaire.",
        amenities: ["Vue mer", "Piscine", "Wifi", "Climatisation", "Groupe électrogène", "Gardien", "Cuisine", "Stationnement"],
        hostId: "h-aminata",
        managedByPlatform: true,
        reviews: [
          review("Claire B.", "2026-08-14", "Photos justes, accueil à l'heure, piscine propre. On a réservé sans courtier et tout était déjà prêt."),
          review("Omar S.", "2026-05-02", "La lumière du matin sur la terrasse vaut le séjour. L'état des lieux d'entrée était déjà dans l'application."),
        ],
      },
      {
        id: "ngor-vue-mer",
        title: "Appartement clair, vue sur Ngor",
        city: "Dakar",
        country: "Sénégal",
        neighborhood: "Ngor",
        mode: "sejour",
        type: "appartement",
        price: 45_000,
        currency: "XOF",
        guests: 4,
        bedrooms: 2,
        beds: 2,
        baths: 1,
        surface: 78,
        rating: 4.88,
        reviewsCount: 21,
        images: img.apt,
        lat: 14.7489,
        lng: -17.5128,
        description:
          "Deux chambres, une cuisine équipée, et une fenêtre qui prend l'île de Ngor. L'immeuble est calme, le gardien connaît les hôtes d'Se Loger au Sénégal.\n\nIdéal pour un séjour de travail ou une semaine en famille proche, sans frais cachés à l'arrivée.",
        amenities: ["Vue mer", "Wifi", "Climatisation", "Cuisine", "Espace de travail", "Gardien"],
        hostId: "h-aminata",
        managedByPlatform: false,
        reviews: [
          review("Awa D.", "2026-07-19", "Exactement les photos. Le prix affiché était le prix payé."),
        ],
      },
      {
        id: "saly-bords",
        title: "Maison les pieds dans le sable, Saly",
        city: "Saly",
        country: "Sénégal",
        neighborhood: "Saly Portudal",
        mode: "sejour",
        type: "maison",
        price: 62_000,
        currency: "XOF",
        guests: 6,
        bedrooms: 3,
        beds: 4,
        baths: 2,
        surface: 160,
        rating: 4.91,
        reviewsCount: 44,
        images: img.beach,
        lat: 14.4486,
        lng: -17.0155,
        description:
          "Une maison basse, ouverte sur la plage de Saly. Les chambres restent fraîches, la terrasse sert de salle à manger, et le soir le bruit est celui de l'eau.\n\nLe bien est géré par Se Loger au Sénégal : remise des clés, ménage, et signalement des pannes au même endroit.",
        amenities: ["Vue mer", "Wifi", "Climatisation", "Cuisine", "Terrasse", "Stationnement"],
        hostId: "h-moussa",
        managedByPlatform: true,
        reviews: [
          review("Inès K.", "2026-04-11", "On est arrivés de nuit, le gardien avait le code. Rien à négocier sur place."),
        ],
      },
      {
        id: "somone-lodge",
        title: "Écolodge au bord de la lagune",
        city: "Somone",
        country: "Sénégal",
        neighborhood: "Lagune",
        mode: "sejour",
        type: "ecolodge",
        price: 38_000,
        currency: "XOF",
        guests: 3,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        surface: 42,
        rating: 4.84,
        reviewsCount: 17,
        images: img.lodge,
        lat: 14.4865,
        lng: -17.0822,
        description:
          "Un lodge en bois au-dessus de la lagune de Somone. Le matin, les oiseaux passent avant les voitures. La cuisine est simple, le lit est bon, la moustiquaire est là.\n\nPublié par Ndar Immobilier, en direct, avec le calendrier à jour.",
        amenities: ["Wifi", "Moustiquaire", "Cuisine", "Terrasse", "Ventilateur"],
        hostId: "h-ndar",
        managedByPlatform: false,
        reviews: [
          review("Lamine T.", "2026-03-22", "Endroit silencieux. La carte correspondait vraiment à la lagune, pas à une route."),
        ],
      },
      {
        id: "saint-louis",
        title: "Maison de l'île, balcon sur le fleuve",
        city: "Saint-Louis",
        country: "Sénégal",
        neighborhood: "Île Nord",
        mode: "sejour",
        type: "maison",
        price: 28_000,
        currency: "XOF",
        guests: 4,
        bedrooms: 2,
        beds: 2,
        baths: 1,
        surface: 110,
        rating: 4.93,
        reviewsCount: 29,
        images: img.colonial,
        lat: 16.0246,
        lng: -16.5046,
        description:
          "Une maison haute sur l'île de Saint-Louis. L'escalier est raide, le balcon donne sur le fleuve, et les murs gardent la fraîcheur.\n\nNdar Immobilier tient les clés, les dates et les états des lieux. Le prix de la nuit est celui de la fiche.",
        amenities: ["Wifi", "Ventilateur", "Cuisine", "Balcon", "Centre-ville"],
        hostId: "h-ndar",
        managedByPlatform: false,
        reviews: [
          review("Marie C.", "2026-02-08", "On entend le fleuve. La maison est fidèle aux photos, y compris l'escalier."),
        ],
      },
      {
        id: "plateau-loft",
        title: "Loft du Plateau, pour rester longtemps",
        city: "Dakar",
        country: "Sénégal",
        neighborhood: "Plateau",
        mode: "location",
        type: "appartement",
        price: 450_000,
        currency: "XOF",
        guests: 3,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        surface: 96,
        rating: 4.8,
        reviewsCount: 9,
        images: img.loft,
        lat: 14.6676,
        lng: -17.4295,
        description:
          "Un loft au Plateau, à dix minutes à pied des bureaux et du marché. Grande hauteur sous plafond, cuisine fermée, deux chambres.\n\nLocation longue durée : deux mois d'avance, propriétaire identifié, visite demandée dans Se Loger au Sénégal. Pas de mois d'agence à verser à un courtier.",
        amenities: ["Wifi", "Climatisation", "Cuisine", "Espace de travail", "Gardien", "Ascenseur"],
        hostId: "h-moussa",
        managedByPlatform: false,
        reviews: [
          review("Jean-Marc C.", "2026-01-18", "Visite le lendemain de la demande. Le loyer affiché n'a pas bougé."),
        ],
      },
      {
        id: "mermoz",
        title: "Appartement familial à Mermoz",
        city: "Dakar",
        country: "Sénégal",
        neighborhood: "Mermoz",
        mode: "location",
        type: "appartement",
        price: 275_000,
        currency: "XOF",
        guests: 4,
        bedrooms: 3,
        beds: 3,
        baths: 2,
        surface: 120,
        rating: 4.86,
        reviewsCount: 11,
        images: img.apt,
        lat: 14.7068,
        lng: -17.4755,
        description:
          "Trois chambres dans un immeuble tenu, près des écoles de Mermoz. Le séjour est lumineux, la cuisine a été refaite, le gardien est sur place.\n\nAminata Diallo loue en direct. L'état des lieux d'entrée, les compteurs et les quittances restent dans le dossier du bien.",
        amenities: ["Wifi", "Climatisation", "Cuisine", "Gardien", "Stationnement", "Balcon"],
        hostId: "h-aminata",
        managedByPlatform: false,
        reviews: [
          review("Fatou S.", "2025-11-03", "Entrée faite avec les index d'eau et d'électricité photographiés. Ça change tout à la sortie."),
        ],
      },
      {
        id: "ouakam",
        title: "Villa familiale à Ouakam",
        city: "Dakar",
        country: "Sénégal",
        neighborhood: "Ouakam",
        mode: "location",
        type: "villa",
        price: 650_000,
        currency: "XOF",
        guests: 7,
        bedrooms: 4,
        beds: 5,
        baths: 3,
        surface: 240,
        rating: 4.9,
        reviewsCount: 6,
        images: img.family,
        lat: 14.7234,
        lng: -17.4922,
        description:
          "Une villa avec cour, pour une famille qui s'installe. Quatre chambres, un bureau, un groupe électrogène, et une cuisine qui peut recevoir.\n\nGérée par Se Loger au Sénégal pour le compte de Ndar Immobilier : loyers, charges, et incidents avec photo arrivent au même endroit.",
        amenities: ["Wifi", "Climatisation", "Groupe électrogène", "Gardien", "Cuisine", "Stationnement", "Cour"],
        hostId: "h-ndar",
        managedByPlatform: true,
        reviews: [
          review("Aïcha B.", "2026-06-01", "La panne de clim a été signalée le soir, le gestionnaire avait la photo le matin."),
        ],
      },
      {
        id: "sacre-coeur",
        title: "Studio meublé, Sacré-Cœur",
        city: "Dakar",
        country: "Sénégal",
        neighborhood: "Sacré-Cœur",
        mode: "location",
        type: "studio",
        price: 180_000,
        currency: "XOF",
        guests: 2,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        surface: 32,
        rating: 4.72,
        reviewsCount: 8,
        images: img.studio,
        lat: 14.7169,
        lng: -17.4628,
        description:
          "Un studio meublé, propre, pour une personne ou un couple. Lit, bureau, kitchenette, climatisation. L'immeuble est gardienné.\n\nLocation directe. Le loyer, les charges et l'état du mobilier sont écrits avant la visite.",
        amenities: ["Wifi", "Climatisation", "Cuisine", "Espace de travail", "Gardien"],
        hostId: "h-aminata",
        managedByPlatform: false,
        reviews: [
          review("Ibrahima F.", "2026-09-12", "Studio conforme. Le dossier de charges est lisible, ce qui est rare."),
        ],
      },
      {
        id: "mbour-ocean",
        title: "Appartement lumineux près de l’océan",
        city: "Mbour",
        country: "Sénégal",
        neighborhood: "Grand Mbour",
        mode: "sejour",
        type: "appartement",
        price: 55_000,
        currency: "XOF",
        guests: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        surface: 90,
        rating: 4.85,
        reviewsCount: 14,
        images: img.abidjan,
        lat: 14.4167,
        lng: -16.9667,
        description:
          "À Grand Mbour, un appartement en étage avec vue dégagée et deux chambres climatisées. La plage, le marché et les transports sont accessibles rapidement.\n\nNdar Immobilier assure la remise des clés sur place.",
        amenities: ["Wifi", "Climatisation", "Cuisine", "Gardien", "Ascenseur", "Stationnement"],
        hostId: "h-ndar",
        managedByPlatform: false,
        reviews: [
          review("Serge K.", "2026-07-02", "Même sérieux qu'à Dakar. La localisation sur la carte était la bonne."),
        ],
      },
      {
        id: "cap-skirring-patio",
        title: "Villa patio sous les palmiers",
        city: "Cap Skirring",
        country: "Sénégal",
        neighborhood: "Kabrousse",
        mode: "sejour",
        type: "riad",
        price: 90_000,
        currency: "XOF",
        guests: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        surface: 140,
        rating: 4.97,
        reviewsCount: 52,
        images: img.riad,
        lat: 12.395,
        lng: -16.742,
        description:
          "Une villa à patio au calme, entre palmiers et plage. Deux suites, un salon bas et le petit-déjeuner servi si vous le demandez.\n\nLe séjour se réserve avec des photos larges, un prix total et un hôte identifié.",
        amenities: ["Wifi", "Patio", "Climatisation", "Petit-déjeuner", "Cuisine"],
        hostId: "h-moussa",
        managedByPlatform: true,
        reviews: [
          review("Leïla M.", "2026-05-28", "Patio silencieux. Le total des nuits était clair avant le paiement."),
        ],
      },
      {
        id: "thies-centre",
        title: "Appartement central, location longue durée",
        city: "Thiès",
        country: "Sénégal",
        neighborhood: "Centre-ville",
        mode: "location",
        type: "appartement",
        price: 280_000,
        currency: "XOF",
        guests: 3,
        bedrooms: 2,
        beds: 2,
        baths: 1,
        surface: 58,
        rating: 4.78,
        reviewsCount: 7,
        images: img.paris,
        lat: 14.791,
        lng: -16.935,
        description:
          "Un appartement lumineux au centre de Thiès, pour une installation durable. Cuisine équipée, deux chambres et accès rapide aux commerces.\n\nAvance, quittances, compteurs et état des lieux restent regroupés dans le dossier.",
        amenities: ["Wifi", "Cuisine", "Chauffage", "Espace de travail", "Machine à laver"],
        hostId: "h-aminata",
        managedByPlatform: false,
        reviews: [
          review("Paul H.", "2026-04-04", "Dossier propre, de la visite jusqu'aux index. On sait à qui on loue."),
        ],
      },
    ],
    reservations: [
      {
        id: "res-claire",
        listingId: "villa-almadies",
        guestName: "Claire Bernard",
        mode: "sejour",
        from: "2026-10-12",
        to: "2026-10-16",
        status: "confirmee",
        subtotal: 340_000,
        commission: 68_000,
        guestPays: 340_000,
        currency: "XOF",
      },
      {
        id: "res-fatou",
        listingId: "mermoz",
        guestName: "Fatou Sarr",
        mode: "location",
        from: "2026-09-01",
        to: "2027-08-31",
        status: "en-cours",
        subtotal: 275_000,
        commission: 55_000,
        guestPays: 550_000,
        currency: "XOF",
      },
      {
        id: "res-paul",
        listingId: "paris-11",
        guestName: "Paul Henry",
        mode: "location",
        from: "2026-03-01",
        to: "2027-02-28",
        status: "en-cours",
        subtotal: 2100,
        commission: 420,
        guestPays: 4200,
        currency: "EUR",
      },
    ],
    invoices: [
      {
        id: "fac-fatou",
        listingId: "mermoz",
        clientName: "Fatou Sarr",
        label: "Loyer octobre",
        amount: 275_000,
        currency: "XOF",
        status: "payee",
        date: "2026-10-02",
        kind: "loyer",
      },
      {
        id: "fac-com-fatou",
        listingId: "mermoz",
        clientName: "Aminata Diallo",
        label: "Commission de mise en location",
        amount: 55_000,
        currency: "XOF",
        status: "payee",
        date: "2026-09-01",
        kind: "commission",
      },
      {
        id: "fac-ibra",
        listingId: "sacre-coeur",
        clientName: "Ibrahima Fall",
        label: "Loyer octobre",
        amount: 180_000,
        currency: "XOF",
        status: "retard",
        date: "2026-10-05",
        kind: "loyer",
      },
      {
        id: "fac-paul",
        listingId: "paris-11",
        clientName: "Paul Henry",
        label: "Loyer octobre",
        amount: 2100,
        currency: "EUR",
        status: "payee",
        date: "2026-10-01",
        kind: "loyer",
      },
      {
        id: "fac-claire",
        listingId: "villa-almadies",
        clientName: "Claire Bernard",
        label: "Séjour 12–16 octobre",
        amount: 340_000,
        currency: "XOF",
        status: "due",
        date: "2026-10-08",
        kind: "sejour",
      },
    ],
    expenses: [
      {
        id: "dep-plomb",
        listingId: "villa-almadies",
        label: "Joint de robinet, cuisine",
        category: "reparation",
        amount: 15_000,
        currency: "XOF",
        date: "2026-09-18",
        chargeToTenant: false,
      },
      {
        id: "dep-eau",
        listingId: "mermoz",
        label: "Facture d'eau septembre",
        category: "autre",
        amount: 18_500,
        currency: "XOF",
        date: "2026-10-03",
        chargeToTenant: true,
      },
      {
        id: "dep-taxe",
        listingId: "mermoz",
        label: "Taxe foncière, acompte",
        category: "taxe",
        amount: 90_000,
        currency: "XOF",
        date: "2026-09-15",
        chargeToTenant: false,
      },
      {
        id: "dep-menage",
        listingId: "villa-almadies",
        label: "Ménage de fin de séjour",
        category: "menage",
        amount: 20_000,
        currency: "XOF",
        date: "2026-09-28",
        chargeToTenant: false,
      },
    ],
    clients: [
      {
        id: "cli-fatou",
        name: "Fatou Sarr",
        email: "fatou.sarr@email.com",
        phone: "+221 77 000 11 22",
        listingId: "mermoz",
        kind: "locataire",
        since: "2026-09-01",
        balance: 0,
        currency: "XOF",
      },
      {
        id: "cli-ibra",
        name: "Ibrahima Fall",
        email: "ibrahima.fall@email.com",
        phone: "+221 76 111 22 33",
        listingId: "sacre-coeur",
        kind: "locataire",
        since: "2026-06-01",
        balance: 180_000,
        currency: "XOF",
      },
      {
        id: "cli-claire",
        name: "Claire Bernard",
        email: "claire.bernard@email.com",
        phone: "+33 6 12 34 56 78",
        listingId: "villa-almadies",
        kind: "voyageur",
        since: "2026-10-08",
        balance: 340_000,
        currency: "XOF",
      },
      {
        id: "cli-paul",
        name: "Paul Henry",
        email: "paul.henry@email.com",
        phone: "+33 6 98 76 54 32",
        listingId: "paris-11",
        kind: "locataire",
        since: "2026-03-01",
        balance: 0,
        currency: "EUR",
      },
    ],
    incidents: [
      {
        id: "inc-fuite",
        listingId: "villa-almadies",
        title: "Fuite sous l'évier de la cuisine",
        category: "panne",
        description: "L'eau perle dès qu'on ouvre l'eau chaude. Le bac est déjà mouillé. Photo prise ce matin.",
        photos: [photo("photo-1585704032915-c3400ca199e7")],
        reporter: "Claire Bernard",
        createdAt: "2026-10-06T08:40:00.000Z",
        status: "nouveau",
        notifiedName: "Aminata Diallo",
      },
      {
        id: "inc-clim",
        listingId: "ouakam",
        title: "Climatisation de la chambre 2 en panne",
        category: "panne",
        description: "L'unité intérieure tourne sans froid. La chambre devient inutilisable l'après-midi.",
        photos: [photo("photo-1631545806609-35d4a0f1c5e1")],
        reporter: "Aïcha Ba",
        createdAt: "2026-10-04T16:10:00.000Z",
        status: "pris-en-charge",
        notifiedName: "Ndar Immobilier",
      },
    ],
    inspections: [
      {
        id: "edl-mermoz",
        listingId: "mermoz",
        kind: "entree",
        date: "2026-09-01",
        author: "Aminata Diallo",
        rooms: [
          { name: "Séjour", state: "bon", notes: "Peinture propre, un micro-impact derrière la porte.", photos: [] },
          { name: "Cuisine", state: "bon", notes: "Électroménager fonctionnel.", photos: [] },
          { name: "Chambre", state: "bon", notes: "Placards vides, serrure ok.", photos: [] },
          { name: "Salle d'eau", state: "use", notes: "Joint de douche à surveiller.", photos: [] },
          { name: "Extérieur", state: "bon", notes: "Balcon dégagé.", photos: [] },
        ],
        meters: [
          { kind: "eau", index: "014582", unit: "m³" },
          { kind: "electricite", index: "22841", unit: "kWh" },
        ],
        keys: 3,
        comments: "Remise des trois jeux de clés. Le locataire reconnaît l'état décrit.",
        tenantSignature: "Fatou Sarr",
        ownerSignature: "Aminata Diallo",
        signedAt: "2026-09-01T10:30:00.000Z",
      },
    ],
    notifications: [
      {
        id: "note-fuite",
        title: "Panne signalée · Villa océan",
        body: "Fuite sous l'évier. Une photo est jointe. Aminata Diallo est notifiée.",
        createdAt: "2026-10-06T08:40:00.000Z",
        read: false,
        href: "/gestion/incidents/inc-fuite",
        audience: "proprietaire",
        listingId: "villa-almadies",
      },
    ],
    settings: {
      advanceMonths: 2,
      rules: [
        {
          id: "rule-sejour",
          label: "Séjour",
          mode: "sejour",
          active: true,
          kind: "percent",
          value: 20,
          payer: "proprietaire",
          ownerShare: 100,
          base: "sejour",
        },
        {
          id: "rule-location",
          label: "Location",
          mode: "location",
          active: true,
          kind: "percent",
          value: 20,
          payer: "proprietaire",
          ownerShare: 100,
          base: "mois",
        },
        {
          id: "rule-gestion",
          label: "Gestion Se Loger au Sénégal",
          mode: "gestion",
          active: true,
          kind: "percent",
          value: 20,
          payer: "proprietaire",
          ownerShare: 100,
          base: "mois",
        },
      ],
      promos: [
        {
          id: "promo-lancement",
          label: "Lancement — commission réduite de 25 %",
          active: false,
          mode: "tous",
          discountPercent: 25,
          target: "commission",
          beneficiary: "proprietaire",
        },
        {
          id: "promo-decouverte",
          label: "Offre découverte — 5 % sur le prix",
          active: false,
          mode: "sejour",
          discountPercent: 5,
          target: "prix",
          beneficiary: "client",
        },
      ],
      ads: [
        {
          id: "ad-sahel",
          placement: "accueil-bandeau",
          partner: "Sahel Assurances",
          title: "Le logement assuré dès la remise des clés",
          subtitle: "Une offre partenaire pour les baux signés sur Se Loger au Sénégal. L'image, le lien et la période se règlent dans l'administration.",
          image: photo("photo-1560518883-ce09059eeffa"),
          href: "/boutiques",
          active: true,
          offer: "Devis offert",
        },
        {
          id: "ad-ndargal",
          placement: "accueil-rangee",
          partner: "Atelier Ndargal",
          title: "Menuiserie et remise en état",
          subtitle: "Portes, placards, reprises après état des lieux de sortie.",
          image: photo("photo-1504148455328-c376907d081c"),
          href: "/boutiques",
          active: true,
        },
        {
          id: "ad-explorer",
          placement: "explorer",
          partner: "Maison Lin",
          title: "Linge de maison pour les séjours gérés",
          subtitle: "Draps, serviettes, reprise chaque lundi à Dakar.",
          image: photo("photo-1522771739844-6a9f6d5f14af"),
          href: "/boutiques",
          active: true,
          offer: "−15 % hôtes",
        },
        {
          id: "ad-fiche",
          placement: "fiche",
          partner: "Vague Pay",
          title: "Encaisser l'avance sans espèces",
          subtitle: "Le locataire règle les deux mois, le propriétaire suit le virement.",
          image: photo("photo-1556742049-0cfed4f6a45d"),
          href: "/boutiques",
          active: true,
        },
        {
          id: "ad-gestion",
          placement: "gestion",
          partner: "Sahel Assurances",
          title: "Déclarez un sinistre depuis l'incident",
          subtitle: "La photo du signalement peut servir de pièce au dossier.",
          image: photo("photo-1450101499163-c8848c66ca85"),
          href: "/boutiques",
          active: true,
        },
        {
          id: "shop-lin",
          placement: "boutique",
          partner: "Maison Lin",
          title: "Linge et entretien",
          subtitle: "Pour les villas et appartements gérés à Dakar, Saly et Somone.",
          image: photo("photo-1522771739844-6a9f6d5f14af"),
          href: "/boutiques",
          active: true,
          offer: "Contrat saison",
        },
        {
          id: "shop-ndargal",
          placement: "boutique",
          partner: "Atelier Ndargal",
          title: "Artisans du bâtiment",
          subtitle: "Intervention après panne ou dégradation constatée à la sortie.",
          image: photo("photo-1503387762-592deb58ef4e"),
          href: "/boutiques",
          active: true,
        },
        {
          id: "shop-vague",
          placement: "boutique",
          partner: "Vague Pay",
          title: "Paiements et quittances",
          subtitle: "Avances, loyers et commissions, avec un reçu dans le dossier.",
          image: photo("photo-1563013544-824ae1b704d3"),
          href: "/boutiques",
          active: true,
        },
      ],
    },
  };
}

export function hostById(id: string) {
  return HOSTS.find((host) => host.id === id);
}

export function hostIdForRole(role: AppState["role"]) {
  if (role === "agence") return "h-ndar";
  return "h-aminata";
}
